### ISSUE TITLE
Craft 4 compatibility

### ISSUE THREAD

**Issue by anita-chouhan** [verbb/scheduler#4]
Kindly let me know if there are plans to upgrade this plugin for Craft CMS version 4. 
If yes, is there an ETA?

**Comment by rungta** [comment]
+1

Hi @engram-design, would be great to know if you’re planning on porting this to Craft 4.

**Comment by rungta** [comment]
The both of us are colleagues so it is really just one! 😄

This plugin provides a good system to ensure caches as busted whenever a scheduled entry goes live (or expires). That is really the only functionality we’re looking for at the moment. Happy to consider alternate strategies if you have any other suggestions.

**Comment by anita-chouhan** [comment]
Hello @engram-design, any updates for us.

**Comment by jan-dh** [comment]
Would love to be able to use this as well
